document.writeln("<div class=\'jianju12 clear\'>&nbsp;</div>");
document.writeln("<div class=\'cen980\'><img src=\'/images/xinnka_70.jpg\' width=\'963\' height=\'95\' /></div>");
document.writeln("<div class=\'jianju12 clear\'>&nbsp;</div>");
document.writeln(" ");
document.writeln(" ");
document.writeln("<div class=\'clear\'>&nbsp;</div>");
document.writeln(" ");
document.writeln(" ");
document.writeln("<div class=\'youshibg\'>");
document.writeln("<div class=\'cen980\'>&nbsp;</div>");
document.writeln("</div>");
document.writeln("<div id=\'footer\'>");
document.writeln("  <div id=\'footerT\'> ");
document.writeln("  <p>");
document.writeln("	<span style=\'font-size:14px;\'>版权所有：金喜试管婴儿生殖中心 </span> ");
document.writeln("</p>");
document.writeln("<p>");
document.writeln("	<span style=\'font-size:14px;\'>电话：<span style=\'white-space:nowrap;\'>13802433646</span> &nbsp;&nbsp;&nbsp;QQ：875957008 <br />");
document.writeln("</span> ");
document.writeln("</p>   </div>");
document.writeln("</div>");